### ISSUE TITLE
PictureURL 

### ISSUE THREAD

**Issue by warwickbuilds** [giuleon/OfficeUIFabricPeoplePickerAddIn#1]
Great example first off thanks!

Placing your code on a page to test, it all seems to work but the Picture URL

Browsing to the URL it's trying to set I get
------------------
Bad Request - Request Too Long
HTTP Error 400. The size of the request headers is too long.
-----------------

Url is: https://tenant-my.sharepoint.com/User%20Photos/Profile%20Pictures/user_email_MThumb.jpg

This is in Office 365

**Comment by warwickbuilds** [comment]
So if I construct the URL like follows it works

<img class="ms-Persona-image" src="https://tenant.sharepoint.com/sites/SiteCollectionName/_layouts/15/userphoto.aspx?accountname='+person.SipAddress+'&size=M&url="' + person.PictureURL + '">'

**Comment by giuleon** [comment]
Thanks for your input but in Office 365 I suggest you to use this other example:
https://github.com/giuleon/SPFx-OfficeUIFabric-PeoplePicker
